src/objects/InternalEvent__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>町名・番地</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>市区群</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>概要</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Event_Date__c</fullName>
        <label>開催日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>場所</label>
        <scale>6</scale>
        <type>Location</type>
    </fields>
    <fields>
        <fullName>Needs__c</fullName>
        <label>ニーズ・対象</label>
        <picklist>
            <picklistValues>
                <fullName>マーケティング</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ソーシャルメディア</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ファイナンス</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>マネージメント</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>プログラミング</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>モバイル</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ウェブデザイン</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web開発</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>オペレーション</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ソリューション営業</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>エンタープライズアーキテクチャ</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>都道府県</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>社内行事</label>
    <nameField>
        <label>社内行事名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/InternalEventAttendee__c.object
<CustomObject>
    <fields>
        <fullName>Check_In_Time__c</fullName>
        <label>チェックイン時間</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Confirmation_Number__c</fullName>
        <label>確認コード</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>InternalEvent__c</fullName>
        <label>社内行事</label>
        <referenceTo>InternalEvent__c</referenceTo>
        <relationshipName>EventAttendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Mobile__c</fullName>
        <label>携帯番号</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Total_Hours__c</fullName>
        <label>総時間</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ユーザ</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Volunteers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>社内行事参加者</label>
    <nameField>
        <displayFormat>IEA-{0000}</displayFormat>
        <label>社内行事参加者番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/OnsiteCheckinClass.cls
global class OnsiteCheckinClass{
        
    @RemoteAction
    global static List<InternalEvent__c> getNearby(String lat, String lon) {
        //geolocationが設定されていない場合は東京とする
        if(lat == null || lon == null || lat.equals('') || lon.equals('')) {
            lat = '35.680638';
            lon = '139.764887';
        }

        // SOQLクエリで近くのイベントを検索
        String queryString =
            'SELECT Id, Name, Description__c, Needs__c, ' +
                'Address__c, City__c, Event_Date__c, State__c ' +
            'FROM InternalEvent__c ' +
            'WHERE DISTANCE(Location__c, GEOLOCATION('+lat+','+lon+'), \'mi\') < 3 ' +
            'ORDER BY DISTANCE(Location__c, GEOLOCATION('+lat+','+lon+'), \'mi\') ' +
            'LIMIT 10';

        // Run and return the query results
        return(database.Query(queryString)); 
    }

    @RemoteAction
    global static InternalEventAttendee__c CreateAttendeeRec(Integer hours, String mobile, String confNum, String eventId){
        InternalEventAttendee__c attendee = new InternalEventAttendee__c();
        attendee.Total_Hours__c = hours;
        attendee.InternalEvent__c = eventId;
        attendee.User__c = UserInfo.getUserId();
        attendee.Confirmation_Number__c = confNum;
        attendee.Mobile__c = mobile;
        attendee.Check_In_Time__c = datetime.now();
        insert attendee;
        
        return attendee;
    }
    
    @RemoteAction
    public static Id makeContentPublic(String contentVersionId) {
        ContentVersion cv = [SELECT ContentDocumentId 
                             FROM ContentVersion 
                             WHERE Id = :contentVersionId];
        ContentDocumentLink cdl = new ContentDocumentLink(
            ContentDocumentId = cv.ContentDocumentId, 
            LinkedEntityId = UserInfo.getOrganizationId(), 
            ShareType = 'V');
        insert cdl;
        
        return cv.ContentDocumentId;
    }
   
}