src/objects/Part_Request__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>取引先責任者</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Part_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>配送リクエスト</label>
    <nameField>
        <displayFormat>PR-{0000000}</displayFormat>
        <label>配送リクエストNo</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OrderController.cls
public class OrderController{
    public Contact c {get;set;}
    public Part_Request__c pr {get;set;}
    
    public OrderController(ApexPages.StandardController controller){
        String cid = controller.getRecord().Id;
        c = [SELECT Name, Id, MailingStreet, MailingCity, MailingState, MailingPostalCode, 
            Phone, Email FROM Contact WHERE Id=: cid];
        pr = new Part_Request__c();
    }
    
    public pageReference submitOrder(){
        update c;

        pr.Contact__c = c.Id;
        insert pr;
        System.debug(pr);
        return new PageReference('/'+pr.id).setRedirect(true);
        
    }
}